version: "3.9"

services:
  api:
    restart: always
    build:
      context: ./api
    command: sh entrypoint.sh
    ports:
      - "8000:8000"
    volumes:
      - ./api:/api
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    volumes:
      - .api/data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}